### ISSUE TITLE
Significant p-value with adonis but all p-values >0.05 using pairwise.adonis

### ISSUE THREAD

**Issue by NaomiVi** [pmartinezarbizu/pairwiseAdonis#27]
Hi ,

This is my first time posting a question here so I hope I am doing this right. I have intensively looked for the answer on diverse R forums and could not find help so I am pretty sure this questions has not been answered yet.

I have a metabarcoding dataset with OTUs reads by treatments and I have been running all my stats in R. I produced a nMDS with clear clusters connected to my treatments as well as adonis and anosim (PERMANOVA) and got significant p-values for both and with r^2~ 80% for adonis when I am testing for 'treatments' as my factors. However, when I run a post hoc PERMANOVA test using the same bray-curtis distance matrix (package vegan) with the function pairwise.Adonis  all the pairwise comparisons between my treatments give me p-values > 0.05, regardless of the correction applied to the p-value or the number of permutations used. Here is my code:

_adonis(BC.matrix ~ Treatments, data = meta_data, permutations = 1000)

anosim(BC.matrix, meta_data$Treatments, permutations = 1000)

pairwise.adonis(BC.matrix, meta_data$Treatments)_

Could you help me understand that please?

Thank you in advance for you help. Naomi

**Comment by pmartinezarbizu** [comment]
HI,
these p-values are Pseudo P-values. They are the number of permutations that the F-value is same or better than the observed F-value divided by the number of permutations+1. This means that the more permutations you do the lower the P value can be. If your P value is not changing, this probably means that you have exhausted the number of posible unique permutations and your P value will not longer change. I am not completelly sure about this explanation, so please double check.

> pairwise.adonis(iris[,1:4],iris$Species,perm=99)
                    pairs Df SumsOfSqs    F.Model        R2 p.value p.adjusted sig
1    setosa vs versicolor  1 1.1937545  552.51266 0.8493496    0.01       0.03   .
2     setosa vs virginica  1 2.0713706 1001.54509 0.9108722    0.01       0.03   .
3 versicolor vs virginica  1 0.2108291   91.82959 0.4837475    0.01       0.03   .
> pairwise.adonis(iris[,1:4],iris$Species,perm=999)
                    pairs Df SumsOfSqs    F.Model        R2 p.value p.adjusted sig
1    setosa vs versicolor  1 1.1937545  552.51266 0.8493496   0.001      0.003   *
2     setosa vs virginica  1 2.0713706 1001.54509 0.9108722   0.001      0.003   *
3 versicolor vs virginica  1 0.2108291   91.82959 0.4837475   0.001      0.003   *

**Comment by Marieag** [comment]
Hi! I have a sort-of-similar issue. 

I've been using pairwise.adonis as a post hoc test after a permanova. 

I've come across something I find a little strange, and I'm not sure if there's a bug, or if I've done something wrong (or that data is just weird like that) - any inputs would be much appreciated. 

So, the issue is, that when I run pairwise.adonis like this: 

`post_hoc_permanova <- pairwise.adonis(t(otu), meta$Fungicide_treatment, sim.function = "vegdist",
                                       sim.method = "bray", p.adjust.m = "fdr", reduce = NULL,
                                       perm = 999); post_hoc_permanova
                                 pairs Df SumsOfSqs   F.Model         R2 p.value p.adjusted sig`

I get this:

>pairs Df SumsOfSqs   F.Model         R2 p.value p.adjusted sig
>Bentonite vs Esquive  1 0.4309946 2.1228348 0.17511043   0.059  0.2400000    
>Bentonite vs Tessior  1 0.2354402 1.1522300 0.10331835   0.266  0.3855556    
>Bentonite vs Control water  1 0.2028768 1.0137438 0.09204353   0.346  0.3855556    
>Bentonite vs Copper oxychloride  1 0.1778650 1.0765919 0.09719523   0.347  0.3855556    
>Esquive vs Tessior  1 0.4197328 1.8764408 0.15799690   0.068  0.2400000    
>Esquive vs Control water  1 0.3258340 1.4845894 0.12926796   0.187  0.3740000    
>Esquive vs Copper oxychloride  1 0.4070595 2.2055388 0.18069983   0.072  0.2400000    
>Tessior vs Control water  1 0.2583331 1.1700713 0.10475057   0.288  0.3855556    
>Tessior vs Copper oxychloride  1 0.3041160 1.6361852 0.14061182   0.113  0.2825000    
>Control water vs Copper oxychloride  1 0.1205611 0.6636605 0.06223571   0.594  0.594000

I get all different p-values, but when they're adjusted, suddenly a lot of them are exactly the same adjusted values. I'm at a loss to explain  why this happens. If anyone can enlighten me, I'm all ears.

My dataset looks like this (sorry for the messy paste, not sure how to make it look pretty here):

` #meta              SampleID Real_Sample_Name Year Location Cultivar Fungicide_treatment
GF.ITS.VL31 GF.ITS.VL31             <NA> 2022   Lisbon    Syrah           Bentonite
GF.ITS.VL32 GF.ITS.VL32             <NA> 2022   Lisbon    Syrah           Bentonite
GF.ITS.VL33 GF.ITS.VL33             <NA> 2022   Lisbon    Syrah           Bentonite
GF.ITS.VL34 GF.ITS.VL34             <NA> 2022   Lisbon    Syrah           Bentonite
GF.ITS.VL35 GF.ITS.VL35             <NA> 2022   Lisbon    Syrah           Bentonite
GF.ITS.VL36 GF.ITS.VL36             <NA> 2022   Lisbon    Syrah           Bentonite`

` #otu                    GF.ITS.VL31  GF.ITS.VL32 GF.ITS.VL33  GF.ITS.VL34  GF.ITS.VL35 GF.ITS.VL36 GF.ITS.VL37  GF.ITS.VL38
g__Kondoa            0.000000000 0.0000000000 0.000000000 0.0000000000 0.0000000000           0 0.000000000 0.0000000000
g__Sarocladium       0.000000000 0.0000000000 0.000000000 0.0000000000 0.0000000000           0 0.000000000 0.0000000000
g__Symmetrospora_1   0.001181818 0.0000000000 0.000000000 0.0000000000 0.0000000000           0 0.000000000 0.0000000000
o__Capnodiales       0.000000000 0.0006363636 0.004272727 0.0006363636 0.0004545455           0 0.001363636 0.0008181818
s__Candida_cretensis 0.000000000 0.0000000000 0.000000000 0.0000000000 0.0000000000           0 0.000000000 0.0000000000
c__Leotiomycetes     0.000000000 0.0000000000 0.001454545 0.0086363636 0.0008181818           0 0.001363636 0.0012727273
                     GF.ITS.VL39  GF.ITS.VL40  GF.ITS.VL41  GF.ITS.VL42  GF.ITS.VL43  GF.ITS.VL44  GF.ITS.VL45
g__Kondoa            0.000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.000000e+00 0.000000e+00
g__Sarocladium       0.000000000 0.0000000000 0.0000000000 0.0025454545 0.0000000000 0.000000e+00 0.000000e+00
g__Symmetrospora_1   0.000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 9.090909e-05 0.000000e+00
o__Capnodiales       0.000000000 0.0005454545 0.0004545455 0.0002727273 0.0042727273 5.181818e-03 9.090909e-05
s__Candida_cretensis 0.000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.000000e+00 0.000000e+00
c__Leotiomycetes     0.001454545 0.0000000000 0.0000000000 0.0000000000 0.0006363636 1.818182e-04 0.000000e+00
                      GF.ITS.VL46 GF.ITS.VL47  GF.ITS.VL48  GF.ITS.VL49  GF.ITS.VL50  GF.ITS.VL51 GF.ITS.VL52
g__Kondoa            0.0000000000           0 0.0000000000 0.0000000000 0.0000000000 0.0000000000           0
g__Sarocladium       0.0000000000           0 0.0000000000 0.0000000000 0.0000000000 0.0000000000           0
g__Symmetrospora_1   0.0000000000           0 0.0000000000 0.0000000000 0.0000000000 0.0000000000           0
o__Capnodiales       0.0007272727           0 0.0000000000 0.0003636364 0.0006363636 0.0000000000           0
s__Candida_cretensis 0.0000000000           0 0.0000000000 0.0000000000 0.0000000000 0.0000000000           0
c__Leotiomycetes     0.0000000000           0 0.0007272727 0.0000000000 0.0000000000 0.0001818182           0
                     GF.ITS.VL53 GF.ITS.VL54 GF.ITS.VL56 GF.ITS.VL57  GF.ITS.VL58  GF.ITS.VL59 GF.ITS.VL60
g__Kondoa                      0           0 0.000000000           0 9.090909e-05 0.0000000000           0
g__Sarocladium                 0           0 0.000000000           0 0.000000e+00 0.0000000000           0
g__Symmetrospora_1             0           0 0.000000000           0 0.000000e+00 0.0000000000           0
o__Capnodiales                 0           0 0.001727273           0 3.636364e-04 0.0000000000           0
s__Candida_cretensis           0           0 0.000000000           0 3.818182e-03 0.0002727273           0
c__Leotiomycetes               0           0 0.000000000           0 0.000000e+00 0.0000000000           0`

**Comment by pmartinezarbizu** [comment]
You are using  fdr which is giving you a probability. see below. Sorry I am not used to this adjustment and dont know exactly how it works. But there is no error in the function.

"The "BH" (aka "fdr") and "BY" method of Benjamini, Hochberg, and Yekutieli control the false discovery rate, the expected proportion of false discoveries amongst the rejected hypotheses. The false discovery rate is a less stringent condition than the family-wise error rate, so these methods are more powerful than the others."

Pe
